# Generated by Django 3.2.16 on 2024-03-19 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page_student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='is_paid',
            field=models.BooleanField(default=False, verbose_name='Поле оплаты'),
        ),
    ]
